import { Dimensions, Platform, StyleSheet } from "react-native";
import { C } from "../components/orders/orderConstants";

const { width } = Dimensions.get("window");

export const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: C.bg },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 24,
    backgroundColor: C.surface,
    ...Platform.select({
      ios: {
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.04,
        shadowRadius: 2,
      },
      android: {
        elevation: 1,
      },
    }),
  },
  headerTitle: {
    fontSize: 32,
    fontWeight: "800",
    color: C.text,
    letterSpacing: -0.8,
  },
  headerSubtitle: {
    fontSize: 14,
    color: C.textSecondary,
    marginTop: 4,
    fontWeight: "500",
  },
  filterBtn: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.surfaceElevated,
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: C.border,
    gap: 10,
  },
  filterBtnActive: {
    borderColor: C.accent,
    backgroundColor: C.accentSoft,
  },
  filterBtnText: {
    fontSize: 15,
    color: C.textSecondary,
    fontWeight: "700",
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.surfaceElevated,
    marginHorizontal: 16,
    marginVertical: 14,
    borderRadius: 16,
    paddingHorizontal: 16,
    height: 52,
    borderWidth: 1,
    borderColor: C.borderLight,
  },
  searchInput: {
    flex: 1,
    fontSize: 15,
    color: "#0f172a",
    paddingVertical: 0,
  },
  searchClear: {
    padding: 4,
  },
  searchClearText: {
    color: "#64748b",
    fontSize: 13,
  },
  activePills: {
    maxHeight: 38,
    marginBottom: 10,
    paddingHorizontal: 16,
  },
  activePill: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "rgba(239,123,26,0.10)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: "#ef7b1a",
  },
  activePillText: {
    fontSize: 12,
    color: "#ef7b1a",
    fontWeight: "600",
  },
  activePillRemove: {
    fontSize: 11,
    color: "#ef7b1a",
  },
  listContent: {
    paddingHorizontal: 16,
    paddingBottom: 24,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
    backgroundColor: "#f6f8fb",
  },
  loadingText: {
    color: "#334155",
    fontSize: 14,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
    gap: 8,
  },
  emptyIcon: {
    fontSize: 48,
    marginBottom: 8,
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 14,
    color: "#334155",
    textAlign: "center",
    lineHeight: 20,
  },
  clearFiltersBtn: {
    marginTop: 16,
    backgroundColor: "rgba(239,123,26,0.10)",
    borderRadius: 10,
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#ef7b1a",
  },
  clearFiltersBtnText: {
    color: "#ef7b1a",
    fontWeight: "600",
    fontSize: 14,
  },
  retryBtn: {
    marginTop: 16,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    paddingHorizontal: 24,
    paddingVertical: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  retryBtnText: {
    color: "#0f172a",
    fontWeight: "600",
    fontSize: 14,
  },
  footerLoader: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 8,
    padding: 16,
  },
  footerLoaderText: {
    color: "#334155",
    fontSize: 13,
  },
});

export const filterStyles = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    elevation: 10,
    backgroundColor: C.surface,
  },
  screen: { flex: 1, backgroundColor: C.surface },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 16,
    gap: 12,
  },
  title: {
    fontSize: 28,
    fontWeight: "800",
    color: C.text,
    letterSpacing: -0.6,
  },
  subtitle: {
    fontSize: 13,
    color: C.textSecondary,
    marginTop: 4,
    fontWeight: "500",
  },
  dismissBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 4,
    flexShrink: 0,
  },
  divider: {
    height: 1,
    backgroundColor: "#e2e8f0",
  },
  section: {
    paddingHorizontal: 20,
    paddingVertical: 18,
    borderBottomWidth: 1,
    borderBottomColor: "#f1f5f9",
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: C.textMuted,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 16,
  },
  statusGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  statusChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderWidth: 1.5,
    borderColor: "transparent",
    gap: 8,
    minHeight: 44,
  },
  statusDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
  },
  statusChipText: {
    fontSize: 14,
    color: "#334155",
    fontWeight: "600",
  },
  dateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    width: "100%",
  },
  dateInput: {
    flex: 1,
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 12,
    paddingVertical: 10,
    justifyContent: "center",
  },
  dateInputActive: {
    borderColor: "#ef7b1a",
    backgroundColor: "rgba(239,123,26,0.05)",
  },
  dateInputLabel: {
    fontSize: 12,
    color: "#64748b",
    marginBottom: 4,
    fontWeight: "600",
  },
  dateInputText: {
    fontSize: 13,
    color: "#0f172a",
    fontWeight: "600",
  },
  dateInputRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  sortList: {
    gap: 8,
  },
  sortRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 12,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 12,
  },
  sortRowActive: {
    borderColor: "#ef7b1a",
    backgroundColor: "rgba(239,123,26,0.05)",
  },
  sortIconBox: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  sortIcon: {
    fontSize: 16,
    color: "#64748b",
  },
  sortLabel: {
    flex: 1,
    fontSize: 15,
    color: "#334155",
    fontWeight: "500",
  },
  sortActivePill: {
    backgroundColor: "#ef7b1a",
    borderRadius: 6,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  sortActivePillText: {
    fontSize: 11,
    color: "#ffffff",
    fontWeight: "700",
  },
  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: Platform.OS === "ios" ? 34 : 20,
    backgroundColor: "#ffffff",
    borderTopWidth: 1,
    borderColor: "#e2e8f0",
  },
  resetBtn: {
    flex: 1,
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  resetBtnText: {
    color: "#1d324e",
    fontWeight: "600",
    fontSize: 15,
  },
  applyBtn: {
    flex: 1.2,
    backgroundColor: "#ef7b1a",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  applyBtnText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
});

export const detailStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: "#f6f8fb",
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 20,
    paddingBottom: 16,
    backgroundColor: "#ffffff",
    borderBottomWidth: 1,
    borderColor: "#e2e8f0",
  },
});

export const newStyles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.4)",
  },
  panel: {
    backgroundColor: "#ffffff",
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    maxHeight: "88%",
    paddingHorizontal: 20,
    paddingBottom: Platform.OS === "ios" ? 34 : 20,
  },
  panelHandle: {
    width: 40,
    height: 4,
    backgroundColor: "#e2e8f0",
    borderRadius: 2,
    alignSelf: "center",
    marginTop: 12,
    marginBottom: 16,
  },
  panelTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: "#0f172a",
  },
  panelSubtitle: {
    fontSize: 13,
    color: "#64748b",
    marginBottom: 16,
  },
  panelActions: {
    flexDirection: "row",
    gap: 12,
    marginTop: 16,
  },
  panelBtnSecondary: {
    flex: 1,
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  panelBtnSecondaryText: {
    color: "#1d324e",
    fontWeight: "600",
    fontSize: 15,
  },
  panelBtnPrimary: {
    flex: 2,
    backgroundColor: "#ef7b1a",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
  },
  panelBtnPrimaryText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  bellBtn: {
    position: "relative",
    padding: 4,
  },
  bellBadge: {
    position: "absolute",
    top: 0,
    right: 0,
    backgroundColor: "#ef4444",
    borderRadius: 9,
    minWidth: 18,
    height: 18,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 3,
  },
  bellBadgeText: {
    color: "#ffffff",
    fontSize: 10,
    fontWeight: "700",
  },
  actionBar: {
    margin: 16,
    backgroundColor: "rgba(245,158,11,0.08)",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(245,158,11,0.3)",
  },
  actionBarLabel: {
    fontSize: 15,
    fontWeight: "700",
    color: "#f59e0b",
  },
  actionBarSub: {
    fontSize: 13,
    color: "#334155",
    marginTop: 4,
  },
  actionBtns: {
    flexDirection: "row",
    gap: 10,
    marginTop: 12,
  },
  cancelActionBtn: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 10,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#ef4444",
  },
  cancelActionBtnText: {
    color: "#ef4444",
    fontWeight: "700",
    fontSize: 15,
  },
  acceptActionBtn: {
    flex: 2,
    backgroundColor: "#10b981",
    borderRadius: 10,
    height: 48,
    justifyContent: "center",
    alignItems: "center",
  },
  acceptActionBtnText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  confirmOverlay: {
    flex: 1,
    backgroundColor: "rgba(15,23,42,0.6)",
    justifyContent: "center",
    padding: 24,
  },
  confirmSheet: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 24,
    alignItems: "center",
  },
  confirmIcon: {
    fontSize: 32,
    marginBottom: 16,
  },
  confirmTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 8,
  },
  confirmSub: {
    fontSize: 14,
    color: "#334155",
    textAlign: "center",
    lineHeight: 20,
    marginBottom: 24,
  },
  confirmBtns: {
    flexDirection: "row",
    gap: 12,
    width: "100%",
  },
  confirmBtnSecondary: {
    flex: 1,
    backgroundColor: "#f1f5f9",
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: "center",
  },
  confirmBtnSecondaryText: {
    color: "#334155",
    fontWeight: "600",
  },
  confirmBtnDanger: {
    flex: 1,
    backgroundColor: "#ef4444",
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: "center",
  },
  confirmBtnDangerText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  timelineContainer: {
    backgroundColor: "#ffffff",
    borderRadius: 14,
    padding: 16,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  sectionTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#0f172a",
    marginBottom: 16,
  },
  timelineDot: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 2,
    borderColor: "#f1f5f9",
    backgroundColor: "#f6f8fb",
    zIndex: 1,
    marginTop: 2,
  },
  timelineLine: {
    flex: 1,
    width: 2,
    backgroundColor: "#e2e8f0",
    marginVertical: 2,
  },
  timelineLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#0f172a",
  },
  timelineTime: {
    fontSize: 12,
    color: "#64748b",
    marginTop: 2,
  },
  timelinePending: {
    fontSize: 12,
    color: "#94a3b8",
    marginTop: 2,
    fontStyle: "italic",
  },
  timelineNote: {
    fontSize: 12,
    color: "#ef4444",
    marginTop: 4,
  },
  updateStatusBtn: {
    backgroundColor: "rgba(239,123,26,0.08)",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#ef7b1a",
  },
  updateStatusBtnText: {
    color: "#ef7b1a",
    fontWeight: "700",
    fontSize: 15,
  },
  updaterSectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#64748b",
    letterSpacing: 1,
    marginBottom: 10,
  },
  statusOption: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f8fafc",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    gap: 12,
  },
  statusOptionLabel: {
    flex: 1,
    fontSize: 15,
    color: "#334155",
    fontWeight: "500",
  },
  statusOptionIcon: {
    fontSize: 18,
  },
  statusOptionCheck: {
    fontSize: 16,
    fontWeight: "700",
  },
  courierChip: {
    backgroundColor: "#f1f5f9",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    marginRight: 8,
    borderWidth: 1,
    borderColor: "#e2e8f0",
  },
  courierChipActive: {
    borderColor: "#ef7b1a",
    backgroundColor: "rgba(239,123,26,0.10)",
  },
  courierChipText: {
    fontSize: 13,
    color: "#334155",
    fontWeight: "500",
  },
  trackingInput: {
    backgroundColor: "#f8fafc",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: "#0f172a",
    fontSize: 14,
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
    marginBottom: 4,
  },
});

export const notifStyles = StyleSheet.create({
  overlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    elevation: 10,
    backgroundColor: "#ffffff",
  },
  screen: { flex: 1, backgroundColor: "#ffffff" },
  header: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 12,
  },
  headerRow1: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 10,
  },
  title: {
    fontSize: 26,
    fontWeight: "800",
    color: "#0f172a",
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 13,
    color: "#64748b",
    marginTop: 2,
  },
  markAllBtn: {
    alignSelf: "flex-start",
    backgroundColor: "rgba(239,123,26,0.10)",
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#ef7b1a",
  },
  markAllText: {
    fontSize: 13,
    color: "#ef7b1a",
    fontWeight: "700",
  },
  dismissBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 4,
    flexShrink: 0,
  },
  divider: {
    height: 1,
    backgroundColor: "#e2e8f0",
  },
  emptyState: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 40,
    backgroundColor: "#ffffff",
  },
  emptyTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0f172a",
    marginTop: 16,
    marginBottom: 8,
  },
  emptySub: {
    fontSize: 14,
    color: "#64748b",
    textAlign: "center",
    lineHeight: 20,
  },
  notifCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#ffffff",
    marginHorizontal: 16,
    marginTop: 12,
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: "#e2e8f0",
    position: "relative",
    overflow: "hidden",
  },
  notifCardUnread: {
    borderColor: "#ef7b1a",
    backgroundColor: "rgba(239,123,26,0.03)",
  },
  unreadDot: {
    position: "absolute",
    top: 12,
    left: 12,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#ef7b1a",
    zIndex: 10,
  },
  notifIconBox: {
    width: 44,
    height: 44,
    borderRadius: 12,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  notifTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#0f172a",
  },
  notifProduct: {
    fontSize: 12,
    color: "#ef7b1a",
    marginTop: 2,
    fontWeight: "600",
  },
  notifMeta: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 5,
    flexWrap: "wrap",
    gap: 4,
  },
  notifOrderId: {
    fontSize: 11,
    color: "#64748b",
    fontFamily: Platform.select({ ios: "Menlo", android: "monospace", default: "monospace" }),
  },
  notifDividerDot: {
    width: 3,
    height: 3,
    borderRadius: 1.5,
    backgroundColor: "#e2e8f0",
    marginHorizontal: 2,
  },
  notifAmount: {
    fontSize: 11,
    color: "#10b981",
    fontWeight: "700",
  },
  notifTime: {
    fontSize: 11,
    color: "#94a3b8",
  },
  notifAction: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "#f1f5f9",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  notifChevron: {
    fontSize: 18,
    color: "#64748b",
    lineHeight: 22,
  },
});
